version: "3.4"

x-common-variables: &shared-variables
  SA_PASSWORD: "A!123456a"
  DB_SERVER: "db"
services:
  database_service:
    build: Database
    environment:
      <<: *shared-variables
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
    - "8181:80"
    depends_on:
    - db
  db:
    ports:
    - "1433:1433"
    image: "microsoft/mssql-server-linux"
    environment:
      <<: *shared-variables
      ACCEPT_EULA: "Y"
