version: "3.4"

x-common-variables: &shared-variables
  POSTGRES_PASSWORD: "A!123456a"
  DB_SERVER: "db"
services:
  database_service:
    build: Database
    environment:
      <<: *shared-variables
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
    - "${DB_SERVICE_PORT}:80"
    depends_on:
    - db
  db:
    ports:
    - "5432:5432"
    image: postgres
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    - ./Database/dbInit:/docker-entrypoint-initdb.d
    environment:
      <<: *shared-variables
      POSTGRES_DB: "AstralTest"
  database_updater:
    build: DatabaseUpdater
    stdin_open: true
    tty: true
    depends_on:
    - database_service
    command: tail -f /dev/null 
    environment:
      DB_SERVICE: "database_service"
      DB_SERVICE_PORT: 80
      DURATION: "00:05:00"
